#!/bin/bash
if [ -d "/run/systemd/system/" ]; then
  # old name, those lines should at some point be removed from postinst
  pkill -f key-mapper-service
  systemctl disable key-mapper 2> /dev/null || true
  systemctl stop key-mapper 2> /dev/null || true

  # The ubuntu package creates those two symlinks that break when installing the .deb
  # built from source. Either ubuntus packages need to be uninstalled with --purge first,
  # or those files need to be unlinked manually.
  unlink /etc/systemd/system/input-remapper.service || true
  unlink /etc/systemd/system/default.target.wants/input-remapper-daemon.service || true

  pkill -f input-remapper-service  # might have been started by the gui previously
  systemctl enable input-remapper
  systemctl start input-remapper
fi

# Optional dependency for Steam appinfo parsing
if ! /usr/bin/python3 -c "import steam" >/dev/null 2>&1; then
  echo "Installing python module 'steam' for Steam game filtering..."
  /usr/bin/python3 -m pip install --break-system-packages steam >/dev/null 2>&1 || true
fi
